-- MySQL Script generated by MySQL Workbench
-- Thu Feb 14 15:59:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fz` DEFAULT CHARACTER SET latin1 ;
USE `fz` ;

-- -----------------------------------------------------
-- Table `fz`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`cliente` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`mesa` (
  `idmesa` INT(11) NOT NULL AUTO_INCREMENT,
  `mesa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`pedido` (
  `idpedido` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL DEFAULT NULL,
  `obs` VARCHAR(45) NULL DEFAULT NULL,
  `mesa_idmesa` INT(11) NOT NULL,
  `cliente_cpf` VARCHAR(45) NOT NULL,
  `atendido` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_mesa_idx` (`mesa_idmesa` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `fz`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_mesa`
    FOREIGN KEY (`mesa_idmesa`)
    REFERENCES `fz`.`mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`tipo` (
  `idtipo` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `desconto` VARCHAR(45) NULL DEFAULT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_idtipo` INT(11) NOT NULL,
  `url_img` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_tipo1_idx` (`tipo_idtipo` ASC) VISIBLE,
  CONSTRAINT `fk_produto_tipo1`
    FOREIGN KEY (`tipo_idtipo`)
    REFERENCES `fz`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`aux_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`aux_pedido` (
  `produto_idproduto` INT(11) NOT NULL,
  `pedido_idpedido` INT(11) NOT NULL,
  PRIMARY KEY (`produto_idproduto`, `pedido_idpedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `fz`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `fz`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fz`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fz`.`login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
